// <auto-generated />
namespace _02._03._2020.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddVisitingArchive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVisitingArchive));
        
        string IMigrationMetadata.Id
        {
            get { return "202003062142200_AddVisitingArchive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
